name: Build
on:
  push:
    branches:
      - main
      - develop
permissions: write-all
jobs:
  unit_test:
    name: Unit Test
    uses: ./.github/workflows/unit_test.yml
    secrets: inherit

  sca_scan:
    name: SCA Scan
    uses: ./.github/workflows/sca_scan.yml
    secrets: inherit
  
  code_scan:
    name: Code Scan
    uses: ./.github/workflows/code_scan.yml
    secrets: inherit

  linter:
    name: Linter
    permissions:
      contents: read
      statuses: write
      packages: read
    uses: ./.github/workflows/linting.yml
    secrets: inherit

  # iac_scan:
  #   name: IAC Scan
  #   uses: ./.github/workflows/iac_scan.yml
  #   secrets: inherit
    
  container_scan:
    name: Container Scan
    uses: ./.github/workflows/container_scan.yml
    secrets: inherit

  sbom:
    name: SBOM generate
    uses: ./.github/workflows/sbom.yml
    secrets: inherit

  deployment:
    name: Deployment
    needs: [unit_test, sca_scan, code_scan,linter, container_scan]
    uses: ./.github/workflows/cd.yml
    secrets: inherit 